[package]
name = "my_editor"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
base64 = "0.22"
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures-util = "0.3"
fuzzy-matcher = "0.3.7"
ignore = "0.4"
regex = "1"
lsp-server = "0.7.8"
lsp-types = "0.97.0"
memmap2 = "0.9"
nix = { version = "0.31.1", features = ["fs", "process", "term"] }
ratatui = "0.29.0"
ropey = "1.6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8"
signal-hook = "0.3.18"
tokio = { version = "1.47.1", features = ["io-util", "macros", "process", "rt", "sync", "time"] }
tree-sitter = "0.25"
tree-sitter-json = "0.24.8"
tree-sitter-md-025 = "0.5.6"
tree-sitter-toml-ng = "0.7.0"
unicode-width = "0.2"
vt100 = "0.15.2"
walkdir = "2.5.0"
